# Development overrides (hot-reload + volume mounts)
# Usage: docker compose -f compose.yaml -f compose.dev.yaml up

services:
  web:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:cached
      - ./migrations:/app/migrations:cached
      - ./alembic.ini:/app/alembic.ini:cached
      - ./.artifacts:/var/lib/skriptoteket/artifacts:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENVIRONMENT=development
      - ENABLE_DOCS=true
      - COOKIE_SECURE=false
      # Ensure container uses the mounted artifacts dir (avoids relying on host-dev `.env` defaults like `/tmp/...`).
      - ARTIFACTS_ROOT=/var/lib/skriptoteket/artifacts
      - WATCHFILES_FORCE_POLLING=true
      - WATCHFILES_POLL_DELAY_MS=300
  frontend:
    environment:
      - VITE_DEV_POLLING=true
      - VITE_DEV_POLLING_INTERVAL=200
