# Observability stack for home server (hemma.hule.education)
# Lifecycle: Independent from application - can be started/stopped separately
#
# Usage:
#   docker compose -f compose.observability.yaml up -d
#   docker compose -f compose.observability.yaml down
#
# Prerequisites:
#   - External network: docker network create hule-network
#   - Application running on hule-network (skriptoteket-web)

name: skriptoteket-observability

services:
  # Metrics collection and storage
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    ports:
      - "9091:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - hule-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Distributed tracing backend
  jaeger:
    image: jaegertracing/jaeger:2.1.0
    container_name: jaeger
    restart: unless-stopped
    environment:
      - JAEGER_LISTEN_HOST=0.0.0.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - hule-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Log aggregation backend
  loki:
    image: grafana/loki:3.2.1
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    networks:
      - hule-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Log collection agent
  promtail:
    image: grafana/promtail:3.2.1
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./observability/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail_positions:/tmp
    networks:
      - hule-network
    depends_on:
      - loki

  # Visualization and dashboards
  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_ROOT_URL=http://hemma.hule.education:3000
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    networks:
      - hule-network
    depends_on:
      - prometheus
      - loki
      - jaeger
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hule-network:
    external: true

volumes:
  prometheus_data:
  loki_data:
  promtail_positions:
  grafana_data:
