# Development overrides (hot-reload + volume mounts)
# Usage: docker compose -f compose.yaml -f compose.dev.yaml up

services:
  web:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:cached
      - ./migrations:/app/migrations:cached
      - ./alembic.ini:/app/alembic.ini:cached
    environment:
      - ENVIRONMENT=development
      - ENABLE_DOCS=true
      - COOKIE_SECURE=false
