from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol


class DockerContainerProtocol(Protocol):
    def put_archive(self, *, path: str, data: bytes) -> bool: ...

    def start(self) -> None: ...

    def wait(self, *, timeout: int) -> object: ...

    def kill(self) -> None: ...

    def logs(self, *, stdout: bool, stderr: bool) -> bytes: ...

    def get_archive(self, *, path: str) -> tuple[Iterable[bytes], object]: ...

    def remove(self, *, force: bool) -> None: ...


class DockerVolumeProtocol(Protocol):
    @property
    def name(self) -> str: ...

    def remove(self, *, force: bool) -> None: ...


class DockerVolumesClientProtocol(Protocol):
    def create(self, **kwargs: object) -> DockerVolumeProtocol: ...


class DockerContainersClientProtocol(Protocol):
    def create(self, **kwargs: object) -> DockerContainerProtocol: ...


class DockerClientProtocol(Protocol):
    @property
    def volumes(self) -> DockerVolumesClientProtocol: ...

    @property
    def containers(self) -> DockerContainersClientProtocol: ...

    def close(self) -> None: ...
