/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suggestions For Review */
        get: operations["list_suggestions_for_review_api_v1_admin_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/suggestions/{suggestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggestion For Review */
        get: operations["get_suggestion_for_review_api_v1_admin_suggestions__suggestion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/suggestions/{suggestion_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Suggestion */
        post: operations["decide_suggestion_api_v1_admin_suggestions__suggestion_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Tools */
        get: operations["list_admin_tools_api_v1_admin_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tools/{tool_id}/depublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Depublish Tool */
        post: operations["depublish_tool_api_v1_admin_tools__tool_id__depublish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tools/{tool_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Tool */
        post: operations["publish_tool_api_v1_admin_tools__tool_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App By Id */
        get: operations["get_app_by_id_api_v1_apps__app_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Categories */
        get: operations["list_all_categories_api_v1_catalog_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/professions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Professions */
        get: operations["list_professions_api_v1_catalog_professions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/professions/{profession_slug}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_catalog_professions__profession_slug__categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/professions/{profession_slug}/categories/{category_slug}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_api_v1_catalog_professions__profession_slug__categories__category_slug__tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_editor_tool_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-runs/{run_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_editor_tool_runs__run_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Editor For Version */
        get: operations["get_editor_for_version_api_v1_editor_tool_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Version */
        post: operations["publish_version_api_v1_editor_tool_versions__version_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Changes */
        post: operations["request_changes_api_v1_editor_tool_versions__version_id__request_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback Version */
        post: operations["rollback_version_api_v1_editor_tool_versions__version_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}/run-sandbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Sandbox */
        post: operations["run_sandbox_api_v1_editor_tool_versions__version_id__run_sandbox_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Draft Version */
        post: operations["save_draft_version_api_v1_editor_tool_versions__version_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}/submit-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review */
        post: operations["submit_review_api_v1_editor_tool_versions__version_id__submit_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tools/{tool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Editor For Tool */
        get: operations["get_editor_for_tool_api_v1_editor_tools__tool_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tools/{tool_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft Version */
        post: operations["create_draft_version_api_v1_editor_tools__tool_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tools/{tool_id}/maintainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tool Maintainers */
        get: operations["list_tool_maintainers_api_v1_editor_tools__tool_id__maintainers_get"];
        put?: never;
        /** Assign Tool Maintainer */
        post: operations["assign_tool_maintainer_api_v1_editor_tools__tool_id__maintainers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tools/{tool_id}/maintainers/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Tool Maintainer */
        delete: operations["remove_tool_maintainer_api_v1_editor_tools__tool_id__maintainers__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tools/{tool_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Tool Metadata */
        patch: operations["update_tool_metadata_api_v1_editor_tools__tool_id__metadata_patch"];
        trace?: never;
    };
    "/api/v1/editor/tools/{tool_id}/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tool Taxonomy */
        get: operations["get_tool_taxonomy_api_v1_editor_tools__tool_id__taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Tool Taxonomy */
        patch: operations["update_tool_taxonomy_api_v1_editor_tools__tool_id__taxonomy_patch"];
        trace?: never;
    };
    "/api/v1/my-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Runs */
        get: operations["list_my_runs_api_v1_my_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/my-tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Tools */
        get: operations["list_my_tools_api_v1_my_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_runs__run_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/start_action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Action */
        post: operations["start_action_api_v1_start_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Suggestion */
        post: operations["submit_suggestion_api_v1_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tool By Slug */
        get: operations["get_tool_by_slug_api_v1_tools__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{slug}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Tool Run */
        post: operations["start_tool_run_api_v1_tools__slug__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{tool_id}/sessions/{context}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session State */
        get: operations["get_session_state_api_v1_tools__tool_id__sessions__context__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminToolItem
         * @description Tool representation for admin list/actions (ADR-0033).
         */
        AdminToolItem: {
            /** Active Version Id */
            active_version_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Has Pending Review */
            has_pending_review: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Published */
            is_published: boolean;
            /** Latest Version State */
            latest_version_state: string | null;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Count */
            version_count: number;
        };
        /**
         * AppDetailResponse
         * @description Response payload for a curated app detail lookup.
         */
        AppDetailResponse: {
            /** App Id */
            app_id: string;
            min_role: components["schemas"]["Role"];
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        /** ArtifactEntry */
        ArtifactEntry: {
            /** Artifact Id */
            artifact_id: string;
            /** Bytes */
            bytes: number;
            /** Download Url */
            download_url: string;
            /** Path */
            path: string;
        };
        /** AssignMaintainerRequest */
        AssignMaintainerRequest: {
            /** Email */
            email: string;
        };
        /**
         * AuthProvider
         * @enum {string}
         */
        AuthProvider: "local" | "huleedu";
        /** Body_run_sandbox_api_v1_editor_tool_versions__version_id__run_sandbox_post */
        Body_run_sandbox_api_v1_editor_tool_versions__version_id__run_sandbox_post: {
            /** Files */
            files: string[];
        };
        /** Body_start_tool_run_api_v1_tools__slug__run_post */
        Body_start_tool_run_api_v1_tools__slug__run_post: {
            /** Files */
            files: string[];
        };
        /**
         * CategoryItem
         * @description Category for API responses.
         */
        CategoryItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
        };
        /** CreateDraftVersionRequest */
        CreateDraftVersionRequest: {
            /** Change Summary */
            change_summary?: string | null;
            /** Derived From Version Id */
            derived_from_version_id?: string | null;
            /**
             * Entrypoint
             * @default run_tool
             */
            entrypoint: string;
            /** Source Code */
            source_code: string;
        };
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /**
         * CuratedAppItem
         * @description Curated app for API responses.
         */
        CuratedAppItem: {
            /** App Id */
            app_id: string;
            min_role: components["schemas"]["Role"];
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        /**
         * DecideSuggestionRequest
         * @description Admin decision payload for a suggestion.
         */
        DecideSuggestionRequest: {
            /** Category Slugs */
            category_slugs?: string[] | null;
            decision: components["schemas"]["SuggestionDecisionType"];
            /** Description */
            description?: string | null;
            /** Profession Slugs */
            profession_slugs?: string[] | null;
            /** Rationale */
            rationale: string;
            /** Title */
            title?: string | null;
        };
        /** DecideSuggestionResponse */
        DecideSuggestionResponse: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Draft Tool Id */
            draft_tool_id?: string | null;
            /**
             * Suggestion Id
             * Format: uuid
             */
            suggestion_id: string;
        };
        /** DepublishToolResponse */
        DepublishToolResponse: {
            tool: components["schemas"]["AdminToolItem"];
        };
        /** EditorBootResponse */
        EditorBootResponse: {
            /** Derived From Version Id */
            derived_from_version_id: string | null;
            /** Entrypoint */
            entrypoint: string;
            /**
             * Save Mode
             * @enum {string}
             */
            save_mode: "snapshot" | "create_draft";
            selected_version: components["schemas"]["EditorVersionSummary"] | null;
            /** Source Code */
            source_code: string;
            tool: components["schemas"]["EditorToolSummary"];
            /** Versions */
            versions: components["schemas"]["EditorVersionSummary"][];
        };
        /** EditorRunDetails */
        EditorRunDetails: {
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactEntry"][];
            /** Error Summary */
            error_summary: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /** Ui Payload */
            ui_payload: {
                [key: string]: unknown;
            } | null;
            /** Version Id */
            version_id: string | null;
        };
        /** EditorToolMetadataRequest */
        EditorToolMetadataRequest: {
            /** Summary */
            summary?: string | null;
            /** Title */
            title: string;
        };
        /** EditorToolMetadataResponse */
        EditorToolMetadataResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** EditorToolSummary */
        EditorToolSummary: {
            /** Active Version Id */
            active_version_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Published */
            is_published: boolean;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** EditorVersionSummary */
        EditorVersionSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            state: components["schemas"]["VersionState"];
            /** Version Number */
            version_number: number;
        };
        /** GetRunResult */
        GetRunResult: {
            run: components["schemas"]["RunDetails"];
        };
        /** GetSessionStateResult */
        GetSessionStateResult: {
            session_state: components["schemas"]["InteractiveSessionState"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InteractiveSessionState */
        InteractiveSessionState: {
            /** Context */
            context: string;
            /** Latest Run Id */
            latest_run_id?: string | null;
            /** State */
            state: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** State Rev */
            state_rev: number;
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        JsonValue: unknown;
        /** ListAdminToolsResponse */
        ListAdminToolsResponse: {
            /** Tools */
            tools: components["schemas"]["AdminToolItem"][];
        };
        /**
         * ListAllCategoriesResponse
         * @description Response for listing all categories (unfiltered).
         */
        ListAllCategoriesResponse: {
            /** Categories */
            categories: components["schemas"]["CategoryItem"][];
        };
        /** ListArtifactsResult */
        ListArtifactsResult: {
            /** Artifacts */
            artifacts: components["schemas"]["RunArtifact"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * ListCategoriesResponse
         * @description Response for listing categories within a profession.
         */
        ListCategoriesResponse: {
            /** Categories */
            categories: components["schemas"]["CategoryItem"][];
            profession: components["schemas"]["ProfessionItem"];
        };
        /** ListMyRunsResponse */
        ListMyRunsResponse: {
            /** Runs */
            runs: components["schemas"]["MyRunItem"][];
        };
        /** ListMyToolsResponse */
        ListMyToolsResponse: {
            /** Tools */
            tools: components["schemas"]["MyToolItem"][];
        };
        /**
         * ListProfessionsResponse
         * @description Response for listing all professions.
         */
        ListProfessionsResponse: {
            /** Professions */
            professions: components["schemas"]["ProfessionItem"][];
        };
        /** ListSuggestionsResponse */
        ListSuggestionsResponse: {
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionSummary"][];
        };
        /**
         * ListToolsResponse
         * @description Response for listing tools within a profession/category.
         */
        ListToolsResponse: {
            category: components["schemas"]["CategoryItem"];
            /** Curated Apps */
            curated_apps: components["schemas"]["CuratedAppItem"][];
            profession: components["schemas"]["ProfessionItem"];
            /** Tools */
            tools: components["schemas"]["ToolItem"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["User"];
        };
        /** MaintainerListResponse */
        MaintainerListResponse: {
            /** Maintainers */
            maintainers: components["schemas"]["MaintainerSummary"][];
            /**
             * Owner User Id
             * Format: uuid
             */
            owner_user_id: string;
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        /** MaintainerSummary */
        MaintainerSummary: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["Role"];
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["User"];
        };
        /** MyRunItem */
        MyRunItem: {
            /** Finished At */
            finished_at: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
            /** Tool Slug */
            tool_slug: string | null;
            /** Tool Title */
            tool_title: string;
        };
        /** MyToolItem */
        MyToolItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Published */
            is_published: boolean;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /**
         * ProfessionItem
         * @description Profession for API responses.
         */
        ProfessionItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
        };
        /** PublishToolResponse */
        PublishToolResponse: {
            tool: components["schemas"]["AdminToolItem"];
        };
        /** PublishVersionRequest */
        PublishVersionRequest: {
            /** Change Summary */
            change_summary?: string | null;
        };
        /** RequestChangesRequest */
        RequestChangesRequest: {
            /** Message */
            message?: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "user" | "contributor" | "admin" | "superuser";
        /** RunArtifact */
        RunArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Bytes */
            bytes: number;
            /** Download Url */
            download_url: string;
            /** Path */
            path: string;
        };
        /** RunDetails */
        RunDetails: {
            /** Artifacts */
            artifacts?: components["schemas"]["RunArtifact"][];
            /** Error Summary */
            error_summary?: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
            /** Tool Slug */
            tool_slug?: string | null;
            /** Tool Title */
            tool_title: string;
            ui_payload?: components["schemas"]["UiPayloadV2"] | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "running" | "succeeded" | "failed" | "timed_out";
        /** SandboxRunResponse */
        SandboxRunResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
        };
        /** SaveDraftVersionRequest */
        SaveDraftVersionRequest: {
            /** Change Summary */
            change_summary?: string | null;
            /**
             * Entrypoint
             * @default run_tool
             */
            entrypoint: string;
            /**
             * Expected Parent Version Id
             * Format: uuid
             */
            expected_parent_version_id: string;
            /** Source Code */
            source_code: string;
        };
        /** SaveResult */
        SaveResult: {
            /** Redirect Url */
            redirect_url: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /**
         * StartActionCommand
         * @description Start an interactive tool turn (ADR-0024).
         */
        StartActionCommand: {
            /** Action Id */
            action_id: string;
            /** Context */
            context: string;
            /** Expected State Rev */
            expected_state_rev: number;
            /** Input */
            input?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        /** StartActionResult */
        StartActionResult: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** State Rev */
            state_rev: number;
        };
        /** StartToolRunResponse */
        StartToolRunResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** SubmitReviewRequest */
        SubmitReviewRequest: {
            /** Review Note */
            review_note?: string | null;
        };
        /**
         * SubmitSuggestionRequest
         * @description Payload for creating a new suggestion (contributor+).
         */
        SubmitSuggestionRequest: {
            /** Category Slugs */
            category_slugs: string[];
            /** Description */
            description: string;
            /** Profession Slugs */
            profession_slugs: string[];
            /** Title */
            title: string;
        };
        /**
         * SubmitSuggestionResponse
         * @description Response after creating a suggestion.
         */
        SubmitSuggestionResponse: {
            /**
             * Suggestion Id
             * Format: uuid
             */
            suggestion_id: string;
        };
        /**
         * SuggestionDecisionItem
         * @description Decision history entry for a suggestion.
         */
        SuggestionDecisionItem: {
            /** Category Slugs */
            category_slugs: string[];
            /** Created Tool Id */
            created_tool_id?: string | null;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /**
             * Decided By User Id
             * Format: uuid
             */
            decided_by_user_id: string;
            decision: components["schemas"]["SuggestionDecisionType"];
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Profession Slugs */
            profession_slugs: string[];
            /** Rationale */
            rationale: string;
            /**
             * Suggestion Id
             * Format: uuid
             */
            suggestion_id: string;
            /** Title */
            title: string;
        };
        /**
         * SuggestionDecisionType
         * @enum {string}
         */
        SuggestionDecisionType: "accept" | "deny";
        /**
         * SuggestionDetail
         * @description Full suggestion detail for admin review.
         */
        SuggestionDetail: {
            /** Category Slugs */
            category_slugs: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Draft Tool Id */
            draft_tool_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Profession Slugs */
            profession_slugs: string[];
            /** Review Rationale */
            review_rationale?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By User Id */
            reviewed_by_user_id?: string | null;
            status: components["schemas"]["SuggestionStatus"];
            /**
             * Submitted By User Id
             * Format: uuid
             */
            submitted_by_user_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SuggestionDetailResponse */
        SuggestionDetailResponse: {
            /** Decisions */
            decisions: components["schemas"]["SuggestionDecisionItem"][];
            suggestion: components["schemas"]["SuggestionDetail"];
        };
        /**
         * SuggestionStatus
         * @enum {string}
         */
        SuggestionStatus: "pending_review" | "accepted" | "denied";
        /**
         * SuggestionSummary
         * @description Minimal suggestion representation for admin list.
         */
        SuggestionSummary: {
            /** Category Slugs */
            category_slugs: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Profession Slugs */
            profession_slugs: string[];
            status: components["schemas"]["SuggestionStatus"];
            /**
             * Submitted By User Id
             * Format: uuid
             */
            submitted_by_user_id: string;
            /** Title */
            title: string;
        };
        /**
         * ToolItem
         * @description Tool for API responses.
         */
        ToolItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** ToolMetadataResponse */
        ToolMetadataResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            upload_constraints: components["schemas"]["UploadConstraints"];
        };
        /** ToolTaxonomyRequest */
        ToolTaxonomyRequest: {
            /** Category Ids */
            category_ids: string[];
            /** Profession Ids */
            profession_ids: string[];
        };
        /** ToolTaxonomyResponse */
        ToolTaxonomyResponse: {
            /** Category Ids */
            category_ids: string[];
            /** Profession Ids */
            profession_ids: string[];
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        /** UiBooleanField */
        UiBooleanField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "boolean";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiEnumField */
        UiEnumField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "enum";
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Options */
            options: components["schemas"]["UiEnumOption"][];
        };
        /** UiEnumOption */
        UiEnumOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** UiFormAction */
        UiFormAction: {
            /** Action Id */
            action_id: string;
            /** Fields */
            fields?: (components["schemas"]["UiStringField"] | components["schemas"]["UiTextField"] | components["schemas"]["UiIntegerField"] | components["schemas"]["UiNumberField"] | components["schemas"]["UiBooleanField"] | components["schemas"]["UiEnumField"] | components["schemas"]["UiMultiEnumField"])[];
            /**
             * Kind
             * @default form
             * @constant
             */
            kind: "form";
            /** Label */
            label: string;
        };
        /** UiHtmlSandboxedOutput */
        UiHtmlSandboxedOutput: {
            /** Html */
            html: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "html_sandboxed";
        };
        /** UiIntegerField */
        UiIntegerField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "integer";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiJsonOutput */
        UiJsonOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "json";
            /** Title */
            title?: string | null;
            value: components["schemas"]["JsonValue"];
        };
        /** UiMarkdownOutput */
        UiMarkdownOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "markdown";
            /** Markdown */
            markdown: string;
        };
        /** UiMultiEnumField */
        UiMultiEnumField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "multi_enum";
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Options */
            options: components["schemas"]["UiEnumOption"][];
        };
        /**
         * UiNoticeLevel
         * @enum {string}
         */
        UiNoticeLevel: "info" | "warning" | "error";
        /** UiNoticeOutput */
        UiNoticeOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "notice";
            level: components["schemas"]["UiNoticeLevel"];
            /** Message */
            message: string;
        };
        /** UiNumberField */
        UiNumberField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "number";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /**
         * UiPayloadV2
         * @description Stored UI payload (rendering source of truth; ADR-0024).
         */
        UiPayloadV2: {
            /**
             * Contract Version
             * @default 2
             * @constant
             */
            contract_version: 2;
            /** Next Actions */
            next_actions?: components["schemas"]["UiFormAction"][];
            /** Outputs */
            outputs?: (components["schemas"]["UiNoticeOutput"] | components["schemas"]["UiMarkdownOutput"] | components["schemas"]["UiTableOutput"] | components["schemas"]["UiJsonOutput"] | components["schemas"]["UiHtmlSandboxedOutput"] | components["schemas"]["UiVegaLiteOutput"])[];
        };
        /** UiStringField */
        UiStringField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "string";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiTableColumn */
        UiTableColumn: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** UiTableOutput */
        UiTableOutput: {
            /** Columns */
            columns: components["schemas"]["UiTableColumn"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table";
            /** Rows */
            rows: {
                [key: string]: string | number | boolean | null;
            }[];
            /** Title */
            title?: string | null;
        };
        /** UiTextField */
        UiTextField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiVegaLiteOutput */
        UiVegaLiteOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "vega_lite";
            spec: components["schemas"]["JsonValue"];
        };
        /** UploadConstraints */
        UploadConstraints: {
            /** Max File Bytes */
            max_file_bytes: number;
            /** Max Files */
            max_files: number;
            /** Max Total Bytes */
            max_total_bytes: number;
        };
        /**
         * User
         * @description Identity used across the application.
         *
         *     For future federation, `external_id` and `auth_provider` are included.
         *     Authorization (role) remains local to Skriptoteket.
         */
        User: {
            auth_provider: components["schemas"]["AuthProvider"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** External Id */
            external_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            role: components["schemas"]["Role"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionState
         * @enum {string}
         */
        VersionState: "draft" | "in_review" | "active" | "archived";
        /** WorkflowActionResponse */
        WorkflowActionResponse: {
            /** Redirect Url */
            redirect_url: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_suggestions_for_review_api_v1_admin_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSuggestionsResponse"];
                };
            };
        };
    };
    get_suggestion_for_review_api_v1_admin_suggestions__suggestion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_suggestion_api_v1_admin_suggestions__suggestion_id__decide_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideSuggestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecideSuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_tools_api_v1_admin_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAdminToolsResponse"];
                };
            };
        };
    };
    depublish_tool_api_v1_admin_tools__tool_id__depublish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepublishToolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_tool_api_v1_admin_tools__tool_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishToolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_by_id_api_v1_apps__app_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    csrf_api_v1_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_all_categories_api_v1_catalog_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAllCategoriesResponse"];
                };
            };
        };
    };
    list_professions_api_v1_catalog_professions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProfessionsResponse"];
                };
            };
        };
    };
    list_categories_api_v1_catalog_professions__profession_slug__categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profession_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_catalog_professions__profession_slug__categories__category_slug__tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profession_slug: string;
                category_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListToolsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_editor_tool_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorRunDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_v1_editor_tool_runs__run_id__artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_editor_for_version_api_v1_editor_tool_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorBootResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_version_api_v1_editor_tool_versions__version_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_changes_api_v1_editor_tool_versions__version_id__request_changes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestChangesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_version_api_v1_editor_tool_versions__version_id__rollback_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_sandbox_api_v1_editor_tool_versions__version_id__run_sandbox_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run_sandbox_api_v1_editor_tool_versions__version_id__run_sandbox_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_version_api_v1_editor_tool_versions__version_id__save_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDraftVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_api_v1_editor_tool_versions__version_id__submit_review_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_editor_for_tool_api_v1_editor_tools__tool_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorBootResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_version_api_v1_editor_tools__tool_id__draft_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tool_maintainers_api_v1_editor_tools__tool_id__maintainers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintainerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_tool_maintainer_api_v1_editor_tools__tool_id__maintainers_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignMaintainerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintainerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tool_maintainer_api_v1_editor_tools__tool_id__maintainers__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintainerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tool_metadata_api_v1_editor_tools__tool_id__metadata_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditorToolMetadataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorToolMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tool_taxonomy_api_v1_editor_tools__tool_id__taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolTaxonomyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tool_taxonomy_api_v1_editor_tools__tool_id__taxonomy_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolTaxonomyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolTaxonomyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_runs_api_v1_my_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMyRunsResponse"];
                };
            };
        };
    };
    list_my_tools_api_v1_my_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMyToolsResponse"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListArtifactsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_v1_runs__run_id__artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_action_api_v1_start_action_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartActionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartActionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_suggestion_api_v1_suggestions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitSuggestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitSuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tool_by_slug_api_v1_tools__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_tool_run_api_v1_tools__slug__run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_start_tool_run_api_v1_tools__slug__run_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartToolRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_state_api_v1_tools__tool_id__sessions__context__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_id: string;
                context: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionStateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
