/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/professions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Professions */
        get: operations["list_professions_api_v1_catalog_professions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/professions/{profession_slug}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_catalog_professions__profession_slug__categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/professions/{profession_slug}/categories/{category_slug}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_api_v1_catalog_professions__profession_slug__categories__category_slug__tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tool-versions/{version_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Draft Version */
        post: operations["save_draft_version_api_v1_editor_tool_versions__version_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editor/tools/{tool_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft Version */
        post: operations["create_draft_version_api_v1_editor_tools__tool_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/my-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Runs */
        get: operations["list_my_runs_api_v1_my_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_runs__run_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/start_action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Action */
        post: operations["start_action_api_v1_start_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tool By Slug */
        get: operations["get_tool_by_slug_api_v1_tools__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{slug}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Tool Run */
        post: operations["start_tool_run_api_v1_tools__slug__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{tool_id}/sessions/{context}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session State */
        get: operations["get_session_state_api_v1_tools__tool_id__sessions__context__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthProvider
         * @enum {string}
         */
        AuthProvider: "local" | "huleedu";
        /** Body_assign_maintainer_admin_tools__tool_id__maintainers_post */
        Body_assign_maintainer_admin_tools__tool_id__maintainers_post: {
            /** User Email */
            user_email: string;
        };
        /** Body_create_draft_admin_tools__tool_id__versions_post */
        Body_create_draft_admin_tools__tool_id__versions_post: {
            /** Change Summary */
            change_summary?: string | null;
            /** Derived From Version Id */
            derived_from_version_id?: string | null;
            /**
             * Entrypoint
             * @default run_tool
             */
            entrypoint: string;
            /** Source Code */
            source_code: string;
        };
        /** Body_decide_suggestion_admin_suggestions__suggestion_id__decision_post */
        Body_decide_suggestion_admin_suggestions__suggestion_id__decision_post: {
            /** Category Slugs */
            category_slugs?: string[] | null;
            /** Decision */
            decision: string;
            /** Description */
            description?: string | null;
            /** Profession Slugs */
            profession_slugs?: string[] | null;
            /** Rationale */
            rationale: string;
            /** Title */
            title?: string | null;
        };
        /** Body_logout_logout_post */
        Body_logout_logout_post: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** Body_publish_version_admin_tool_versions__version_id__publish_post */
        Body_publish_version_admin_tool_versions__version_id__publish_post: {
            /** Change Summary */
            change_summary?: string | null;
        };
        /** Body_request_changes_admin_tool_versions__version_id__request_changes_post */
        Body_request_changes_admin_tool_versions__version_id__request_changes_post: {
            /** Message */
            message?: string | null;
        };
        /** Body_run_sandbox_admin_tool_versions__version_id__run_sandbox_post */
        Body_run_sandbox_admin_tool_versions__version_id__run_sandbox_post: {
            /** Files */
            files: string[];
            /** Tool Id */
            tool_id: string;
        };
        /** Body_save_draft_admin_tool_versions__version_id__save_post */
        Body_save_draft_admin_tool_versions__version_id__save_post: {
            /** Change Summary */
            change_summary?: string | null;
            /**
             * Entrypoint
             * @default run_tool
             */
            entrypoint: string;
            /** Expected Parent Version Id */
            expected_parent_version_id: string;
            /** Source Code */
            source_code: string;
        };
        /** Body_start_tool_run_api_v1_tools__slug__run_post */
        Body_start_tool_run_api_v1_tools__slug__run_post: {
            /** Files */
            files: string[];
        };
        /** Body_submit_review_admin_tool_versions__version_id__submit_review_post */
        Body_submit_review_admin_tool_versions__version_id__submit_review_post: {
            /** Review Note */
            review_note?: string | null;
        };
        /** Body_submit_suggestion_suggestions_new_post */
        Body_submit_suggestion_suggestions_new_post: {
            /** Category Slugs */
            category_slugs?: string[] | null;
            /** Description */
            description: string;
            /** Profession Slugs */
            profession_slugs?: string[] | null;
            /** Title */
            title: string;
        };
        /** Body_update_tool_metadata_admin_tools__tool_id__metadata_post */
        Body_update_tool_metadata_admin_tools__tool_id__metadata_post: {
            /** Summary */
            summary?: string | null;
            /** Title */
            title: string;
        };
        /**
         * CategoryItem
         * @description Category for API responses.
         */
        CategoryItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
        };
        /** CreateDraftVersionRequest */
        CreateDraftVersionRequest: {
            /** Change Summary */
            change_summary?: string | null;
            /** Derived From Version Id */
            derived_from_version_id?: string | null;
            /**
             * Entrypoint
             * @default run_tool
             */
            entrypoint: string;
            /** Source Code */
            source_code: string;
        };
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /**
         * CuratedAppItem
         * @description Curated app for API responses.
         */
        CuratedAppItem: {
            /** App Id */
            app_id: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        /** GetRunResult */
        GetRunResult: {
            run: components["schemas"]["RunDetails"];
        };
        /** GetSessionStateResult */
        GetSessionStateResult: {
            session_state: components["schemas"]["InteractiveSessionState"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InteractiveSessionState */
        InteractiveSessionState: {
            /** Context */
            context: string;
            /** Latest Run Id */
            latest_run_id?: string | null;
            /** State */
            state: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** State Rev */
            state_rev: number;
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        JsonValue: unknown;
        /** ListArtifactsResult */
        ListArtifactsResult: {
            /** Artifacts */
            artifacts: components["schemas"]["RunArtifact"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * ListCategoriesResponse
         * @description Response for listing categories within a profession.
         */
        ListCategoriesResponse: {
            /** Categories */
            categories: components["schemas"]["CategoryItem"][];
            profession: components["schemas"]["ProfessionItem"];
        };
        /** ListMyRunsResponse */
        ListMyRunsResponse: {
            /** Runs */
            runs: components["schemas"]["MyRunItem"][];
        };
        /**
         * ListProfessionsResponse
         * @description Response for listing all professions.
         */
        ListProfessionsResponse: {
            /** Professions */
            professions: components["schemas"]["ProfessionItem"][];
        };
        /**
         * ListToolsResponse
         * @description Response for listing tools within a profession/category.
         */
        ListToolsResponse: {
            category: components["schemas"]["CategoryItem"];
            /** Curated Apps */
            curated_apps: components["schemas"]["CuratedAppItem"][];
            profession: components["schemas"]["ProfessionItem"];
            /** Tools */
            tools: components["schemas"]["ToolItem"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["User"];
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["User"];
        };
        /** MyRunItem */
        MyRunItem: {
            /** Finished At */
            finished_at: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
            /** Tool Slug */
            tool_slug: string | null;
            /** Tool Title */
            tool_title: string;
        };
        /**
         * ProfessionItem
         * @description Profession for API responses.
         */
        ProfessionItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "user" | "contributor" | "admin" | "superuser";
        /** RunArtifact */
        RunArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Bytes */
            bytes: number;
            /** Download Url */
            download_url: string;
            /** Path */
            path: string;
        };
        /** RunDetails */
        RunDetails: {
            /** Artifacts */
            artifacts?: components["schemas"]["RunArtifact"][];
            /** Error Summary */
            error_summary?: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
            /** Tool Slug */
            tool_slug?: string | null;
            /** Tool Title */
            tool_title: string;
            ui_payload?: components["schemas"]["UiPayloadV2"] | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "running" | "succeeded" | "failed" | "timed_out";
        /** SaveDraftVersionRequest */
        SaveDraftVersionRequest: {
            /** Change Summary */
            change_summary?: string | null;
            /**
             * Entrypoint
             * @default run_tool
             */
            entrypoint: string;
            /**
             * Expected Parent Version Id
             * Format: uuid
             */
            expected_parent_version_id: string;
            /** Source Code */
            source_code: string;
        };
        /** SaveResult */
        SaveResult: {
            /** Redirect Url */
            redirect_url: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /**
         * StartActionCommand
         * @description Start an interactive tool turn (ADR-0024).
         */
        StartActionCommand: {
            /** Action Id */
            action_id: string;
            /** Context */
            context: string;
            /** Expected State Rev */
            expected_state_rev: number;
            /** Input */
            input?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Tool Id
             * Format: uuid
             */
            tool_id: string;
        };
        /** StartActionResult */
        StartActionResult: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** State Rev */
            state_rev: number;
        };
        /** StartToolRunResponse */
        StartToolRunResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * ToolItem
         * @description Tool for API responses.
         */
        ToolItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** ToolMetadataResponse */
        ToolMetadataResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            upload_constraints: components["schemas"]["UploadConstraints"];
        };
        /** UiBooleanField */
        UiBooleanField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "boolean";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiEnumField */
        UiEnumField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "enum";
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Options */
            options: components["schemas"]["UiEnumOption"][];
        };
        /** UiEnumOption */
        UiEnumOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** UiFormAction */
        UiFormAction: {
            /** Action Id */
            action_id: string;
            /** Fields */
            fields?: (components["schemas"]["UiStringField"] | components["schemas"]["UiTextField"] | components["schemas"]["UiIntegerField"] | components["schemas"]["UiNumberField"] | components["schemas"]["UiBooleanField"] | components["schemas"]["UiEnumField"] | components["schemas"]["UiMultiEnumField"])[];
            /**
             * Kind
             * @default form
             * @constant
             */
            kind: "form";
            /** Label */
            label: string;
        };
        /** UiHtmlSandboxedOutput */
        UiHtmlSandboxedOutput: {
            /** Html */
            html: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "html_sandboxed";
        };
        /** UiIntegerField */
        UiIntegerField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "integer";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiJsonOutput */
        UiJsonOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "json";
            /** Title */
            title?: string | null;
            value: components["schemas"]["JsonValue"];
        };
        /** UiMarkdownOutput */
        UiMarkdownOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "markdown";
            /** Markdown */
            markdown: string;
        };
        /** UiMultiEnumField */
        UiMultiEnumField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "multi_enum";
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Options */
            options: components["schemas"]["UiEnumOption"][];
        };
        /**
         * UiNoticeLevel
         * @enum {string}
         */
        UiNoticeLevel: "info" | "warning" | "error";
        /** UiNoticeOutput */
        UiNoticeOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "notice";
            level: components["schemas"]["UiNoticeLevel"];
            /** Message */
            message: string;
        };
        /** UiNumberField */
        UiNumberField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "number";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /**
         * UiPayloadV2
         * @description Stored UI payload (rendering source of truth; ADR-0024).
         */
        UiPayloadV2: {
            /**
             * Contract Version
             * @default 2
             * @constant
             */
            contract_version: 2;
            /** Next Actions */
            next_actions?: components["schemas"]["UiFormAction"][];
            /** Outputs */
            outputs?: (components["schemas"]["UiNoticeOutput"] | components["schemas"]["UiMarkdownOutput"] | components["schemas"]["UiTableOutput"] | components["schemas"]["UiJsonOutput"] | components["schemas"]["UiHtmlSandboxedOutput"] | components["schemas"]["UiVegaLiteOutput"])[];
        };
        /** UiStringField */
        UiStringField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "string";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiTableColumn */
        UiTableColumn: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** UiTableOutput */
        UiTableOutput: {
            /** Columns */
            columns: components["schemas"]["UiTableColumn"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table";
            /** Rows */
            rows: {
                [key: string]: string | number | boolean | null;
            }[];
            /** Title */
            title?: string | null;
        };
        /** UiTextField */
        UiTextField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UiVegaLiteOutput */
        UiVegaLiteOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "vega_lite";
            spec: components["schemas"]["JsonValue"];
        };
        /** UploadConstraints */
        UploadConstraints: {
            /** Max File Bytes */
            max_file_bytes: number;
            /** Max Files */
            max_files: number;
            /** Max Total Bytes */
            max_total_bytes: number;
        };
        /**
         * User
         * @description Identity used across the application.
         *
         *     For future federation, `external_id` and `auth_provider` are included.
         *     Authorization (role) remains local to Skriptoteket.
         */
        User: {
            auth_provider: components["schemas"]["AuthProvider"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** External Id */
            external_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            role: components["schemas"]["Role"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrf_api_v1_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_professions_api_v1_catalog_professions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProfessionsResponse"];
                };
            };
        };
    };
    list_categories_api_v1_catalog_professions__profession_slug__categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profession_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_catalog_professions__profession_slug__categories__category_slug__tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profession_slug: string;
                category_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListToolsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_version_api_v1_editor_tool_versions__version_id__save_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDraftVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_version_api_v1_editor_tools__tool_id__draft_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_runs_api_v1_my_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMyRunsResponse"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListArtifactsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_v1_runs__run_id__artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_action_api_v1_start_action_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartActionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartActionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tool_by_slug_api_v1_tools__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_tool_run_api_v1_tools__slug__run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_start_tool_run_api_v1_tools__slug__run_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartToolRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_state_api_v1_tools__tool_id__sessions__context__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_id: string;
                context: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionStateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
