/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readycheck */
        get: operations["readycheck_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_v2_convert_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v2_convert_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_v2_convert_jobs__job_id__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/artifact/partial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Partial Artifact */
        get: operations["get_partial_artifact_v2_convert_jobs__job_id__artifact_partial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Bundle Manifest */
        get: operations["get_artifact_bundle_manifest_v2_convert_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/artifacts/{artifact_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Named Artifact */
        get: operations["get_named_artifact_v2_convert_jobs__job_id__artifacts__artifact_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_v2_convert_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint */
        get: operations["get_checkpoint_v2_convert_jobs__job_id__checkpoint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Job Events */
        get: operations["stream_job_events_v2_convert_jobs__job_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_v2_convert_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/convert/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resume_job_v2_convert_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/push/webhooks/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscriptions */
        get: operations["list_subscriptions_v2_push_webhooks_subscriptions_get"];
        put?: never;
        /** Create Subscription */
        post: operations["create_subscription_v2_push_webhooks_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/push/webhooks/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscription */
        get: operations["get_subscription_v2_push_webhooks_subscriptions__subscription_id__get"];
        put?: never;
        post?: never;
        /** Delete Subscription */
        delete: operations["delete_subscription_v2_push_webhooks_subscriptions__subscription_id__delete"];
        options?: never;
        head?: never;
        /** Update Subscription */
        patch: operations["update_subscription_v2_push_webhooks_subscriptions__subscription_id__patch"];
        trace?: never;
    };
    "/v2/push/webhooks/subscriptions/{subscription_id}/revoke-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Secret */
        post: operations["revoke_secret_v2_push_webhooks_subscriptions__subscription_id__revoke_secret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/push/webhooks/subscriptions/{subscription_id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Secret */
        post: operations["rotate_secret_v2_push_webhooks_subscriptions__subscription_id__rotate_secret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/templates/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Docx Templates */
        get: operations["list_docx_templates_v2_templates_docx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/templates/docx/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Docx Template */
        get: operations["get_docx_template_v2_templates_docx__template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/templates/docx/{template_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Docx Template Version */
        get: operations["get_docx_template_version_v2_templates_docx__template_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccelerationPolicy
         * @description Execution acceleration policies supported by v1.
         * @enum {string}
         */
        AccelerationPolicy: "gpu_required" | "gpu_prefer" | "cpu_only";
        /**
         * ArtifactMetadataV2
         * @description Artifact metadata for successful v2 job results.
         */
        ArtifactMetadataV2: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            format: components["schemas"]["OutputFormatV2"];
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * BackendStrategy
         * @description Backend strategy values supported by v1.
         * @enum {string}
         */
        BackendStrategy: "auto" | "docling" | "pymupdf";
        /** Body_create_job_v2_convert_jobs_post */
        Body_create_job_v2_convert_jobs_post: {
            /** @description Optional multipart JSON part carrying a source-bound teacher ingestion overlay. */
            digiexam_ingestion_overlay?: components["schemas"]["DigiExamIngestionOverlay"];
            /** File */
            file: string;
            /** Graded Result Pdf */
            graded_result_pdf?: string | null;
            /** @description Multipart JSON part parsed as the v2 job specification. */
            job_spec: components["schemas"]["JobSpecV2"];
            /** Parity Pdf */
            parity_pdf?: string | null;
            /** Reference Docx */
            reference_docx?: string | null;
            /** Resources */
            resources?: string | null;
        };
        /**
         * ConversionMetadataV2
         * @description Execution metadata for successful v2 conversion jobs.
         */
        ConversionMetadataV2: {
            /** Acceleration Policy Requested */
            acceleration_policy_requested?: string | null;
            /** Acceleration Used */
            acceleration_used?: string | null;
            /** Backend Used */
            backend_used?: string | null;
            /** Chunk Size Pages */
            chunk_size_pages?: number | null;
            /** Effective Gpu Stage Limit */
            effective_gpu_stage_limit?: number | null;
            /** Gpu Busy Percent */
            gpu_busy_percent?: number | null;
            /** Gpu Device Count */
            gpu_device_count?: number | null;
            /** Gpu Memory Used Percent */
            gpu_memory_used_percent?: number | null;
            /** Gpu Runtime Kind */
            gpu_runtime_kind?: string | null;
            /** Max Chunk Workers */
            max_chunk_workers?: number | null;
            /** Ocr Enabled */
            ocr_enabled?: boolean | null;
            /** Ocr Engine Used */
            ocr_engine_used?: string | null;
            /** Ocr Languages Used */
            ocr_languages_used?: string[] | null;
            /** Options Fingerprint */
            options_fingerprint: string;
            /** Parallel Enabled */
            parallel_enabled?: boolean | null;
            /** Pipeline Used */
            pipeline_used: string;
            /** Scheduling Mode */
            scheduling_mode?: string | null;
            /** Template Artifact Sha256 */
            template_artifact_sha256?: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Template Version */
            template_version?: string | null;
        };
        /**
         * ConversionSpecV2
         * @description Conversion section of the v2 job specification.
         */
        ConversionSpecV2: {
            /**
             * Artifact Language
             * @default null
             */
            artifact_language: string | null;
            /** Css Filenames */
            css_filenames?: string[];
            output_format: components["schemas"]["OutputFormatV2"];
            /** @default null */
            page_css_mode: components["schemas"]["PdfPageCssModeV2"] | null;
            /** @default null */
            pdf_layout: components["schemas"]["PdfLayoutV2"] | null;
            /**
             * Reference Docx Filename
             * @default null
             */
            reference_docx_filename: string | null;
            /** Targets */
            targets?: components["schemas"]["ExamMigrationTargetV2"][];
            /** @default null */
            template: components["schemas"]["TemplateSelectorV2"] | null;
        };
        /**
         * DigiExamAnswerKeyCompletionModeV2
         * @description Allowed answer-key completion modes for DigiExam migration.
         * @enum {string}
         */
        DigiExamAnswerKeyCompletionModeV2: "source_evidence_only" | "local_llm_suggest_missing_machine_marked" | "local_llm_apply_missing_machine_marked_with_review";
        /**
         * DigiExamAnswerKeyCompletionReportItemV1
         * @description One advisory answer-key candidate lineage report item.
         */
        DigiExamAnswerKeyCompletionReportItemV1: {
            /**
             * Answer Payload
             * @default null
             */
            answer_payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Backend Failure Code
             * @default null
             */
            backend_failure_code: string | null;
            /** Backend Status */
            backend_status: string;
            /**
             * Candidate Id
             * @default null
             */
            candidate_id: string | null;
            /**
             * Candidate Payload Digest
             * @default null
             */
            candidate_payload_digest: string | null;
            /**
             * Decision State
             * @enum {string}
             */
            decision_state: "suggested" | "manual_follow_up_required" | "skipped";
            /** Item Id */
            item_id: string;
            /** Item Type */
            item_type: string;
            /**
             * Model Profile
             * @default null
             */
            model_profile: string | null;
            /**
             * Prompt Template Version
             * @default null
             */
            prompt_template_version: string | null;
            /**
             * Provider Profile Id
             * @default null
             */
            provider_profile_id: string | null;
            /**
             * Schema Name
             * @default null
             */
            schema_name: "digiexam_choice_answer_key_decision_v1" | "digiexam_gap_fill_answer_key_decision_v1" | null;
            /**
             * Schema Version
             * @default null
             */
            schema_version: "digiexam_choice_answer_key_decision_v1" | "digiexam_gap_fill_answer_key_decision_v1" | null;
            /** Sequence */
            sequence: number;
            /**
             * Validation State
             * @enum {string}
             */
            validation_state: "valid" | "invalid" | "manual_follow_up_required" | "skipped";
        };
        /**
         * DigiExamAnswerKeyCompletionReportV1
         * @description Advisory answer-key completion report without source provenance.
         */
        DigiExamAnswerKeyCompletionReportV1: {
            /**
             * Completion Mode
             * @constant
             */
            completion_mode: "local_llm_suggest_missing_machine_marked";
            /** Items */
            items: components["schemas"]["DigiExamAnswerKeyCompletionReportItemV1"][];
            /** Job Id */
            job_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "answer_key_completion_report_v1";
        };
        /**
         * DigiExamEffectiveAnswerKeyLineageV1
         * @description Bounded reviewed-completion lineage in effective exam artifacts.
         */
        DigiExamEffectiveAnswerKeyLineageV1: {
            /** Candidate Id */
            candidate_id: string;
            /** Candidate Payload Digest */
            candidate_payload_digest: string;
            /** Completion Report Sha256 */
            completion_report_sha256: string;
            /** Prompt Template Version */
            prompt_template_version: string;
            /** Provider Profile Id */
            provider_profile_id: string;
            /** Review Decision Id */
            review_decision_id: string;
            /**
             * Review Outcome
             * @enum {string}
             */
            review_outcome: "accepted_unchanged" | "teacher_edited";
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            /**
             * Validation State
             * @constant
             */
            validation_state: "valid";
        };
        /**
         * DigiExamEffectiveAnswerKeyV1
         * @description Effective answer-key summary without changing source provenance.
         */
        DigiExamEffectiveAnswerKeyV1: {
            /** Correct Alternative Ids */
            correct_alternative_ids?: number[];
            /** Correct Gap Answers */
            correct_gap_answers?: {
                [key: string]: string;
            }[];
            /** @default null */
            lineage: components["schemas"]["DigiExamEffectiveAnswerKeyLineageV1"] | null;
            /** Provenance */
            provenance: string;
        };
        /**
         * DigiExamEffectiveExamV1
         * @description Effective exam artifact emitted when overlay changes renderer input.
         */
        DigiExamEffectiveExamV1: {
            /**
             * Answer Key Completion Report Sha256
             * @default null
             */
            answer_key_completion_report_sha256: string | null;
            /**
             * Ingestion Overlay Sha256
             * @default null
             */
            ingestion_overlay_sha256: string | null;
            /** Items */
            items: components["schemas"]["DigiExamEffectiveItemV1"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "digiexam_effective_exam_v2";
            /** Source File Sha256 */
            source_file_sha256: string;
            /**
             * Source Ir Schema Version
             * @constant
             */
            source_ir_schema_version: "digiexam_intermediate_exam_v3";
            /** Source Ir Sha256 */
            source_ir_sha256: string;
        };
        /**
         * DigiExamEffectiveItemPatchSummaryV1
         * @description Visible effective item patch summary for teacher-review consumers.
         */
        DigiExamEffectiveItemPatchSummaryV1: {
            /** Changed Fields */
            changed_fields?: string[];
            /** Patched Alternative Ids */
            patched_alternative_ids?: number[];
            /** Patched Gap Ids */
            patched_gap_ids?: string[];
        };
        /**
         * DigiExamEffectiveItemV1
         * @description One item summary in current effective exam artifacts.
         */
        DigiExamEffectiveItemV1: {
            /** Applied Overlay Entry Ids */
            applied_overlay_entry_ids?: string[];
            /** @default null */
            effective_answer_key: components["schemas"]["DigiExamEffectiveAnswerKeyV1"] | null;
            /** @default null */
            effective_item_patch: components["schemas"]["DigiExamEffectiveItemPatchSummaryV1"] | null;
            /** Item Id */
            item_id: string;
            /** Item Type */
            item_type: string;
            /** Review Decisions */
            review_decisions?: components["schemas"]["DigiExamEffectiveReviewDecisionV1"][];
            /** Sequence */
            sequence: number;
            /** Source Item Fingerprint */
            source_item_fingerprint: string;
        };
        /**
         * DigiExamEffectiveReviewDecisionV1
         * @description Applied review decision surfaced in effective exam artifacts.
         */
        DigiExamEffectiveReviewDecisionV1: {
            /** Accepted Targets */
            accepted_targets: string[];
            /** Decision Id */
            decision_id: string;
            /** Kind */
            kind: string;
            /**
             * Note
             * @default null
             */
            note: string | null;
        };
        /**
         * DigiExamIngestionOverlay
         * @description Top-level source-bound ingestion overlay.
         */
        DigiExamIngestionOverlay: {
            /** Items */
            items: components["schemas"]["DigiExamIngestionOverlayItem"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "digiexam_ingestion_overlay_v2";
            source_binding: components["schemas"]["DigiExamOverlaySourceBinding"];
        };
        /**
         * DigiExamIngestionOverlayAcceptedEntryV1
         * @description Accepted overlay entry summary excluding raw overlay payloads.
         */
        DigiExamIngestionOverlayAcceptedEntryV1: {
            /** Applied Fields */
            applied_fields: string[];
            /** Item Id */
            item_id: string;
            /** Sequence */
            sequence: number;
        };
        /**
         * DigiExamIngestionOverlayItem
         * @description One source-bound overlay entry for a DigiExam item.
         */
        DigiExamIngestionOverlayItem: {
            /**
             * Effective Item Patch
             * @default null
             */
            effective_item_patch: (components["schemas"]["DigiExamOverlayChoiceItemPatch"] | components["schemas"]["DigiExamOverlayGapFillItemPatch"]) | null;
            /** Item Id */
            item_id: string;
            item_type: components["schemas"]["DigiExamItemType"];
            /**
             * Manual Answer Key
             * @default null
             */
            manual_answer_key: (components["schemas"]["DigiExamOverlayChoiceManualAnswerKey"] | components["schemas"]["DigiExamOverlayGapFillManualAnswerKey"]) | null;
            /** @default null */
            review_decision: components["schemas"]["DigiExamOverlayReviewDecision"] | null;
            /** @default null */
            reviewed_completion_answer_key: components["schemas"]["DigiExamOverlayReviewedCompletionAnswerKey"] | null;
            /** Sequence */
            sequence: number;
            /** Source Item Fingerprint */
            source_item_fingerprint: string;
        };
        /**
         * DigiExamIngestionOverlayPolicyV2
         * @description Allowed teacher overlay application policies for DigiExam migration.
         * @enum {string}
         */
        DigiExamIngestionOverlayPolicyV2: "none" | "apply_teacher_overlay";
        /**
         * DigiExamIngestionOverlayRejectedEntryV1
         * @description Rejected overlay entry summary with stable reason fields.
         */
        DigiExamIngestionOverlayRejectedEntryV1: {
            /** Item Id */
            item_id: string;
            /** Message */
            message: string;
            /** Reason Code */
            reason_code: string;
            /** Sequence */
            sequence: number;
        };
        /**
         * DigiExamIngestionOverlayReportV1
         * @description Overlay application report emitted beside effective IR artifacts.
         */
        DigiExamIngestionOverlayReportV1: {
            /** Accepted Entries */
            accepted_entries: components["schemas"]["DigiExamIngestionOverlayAcceptedEntryV1"][];
            /** Overlay Sha256 */
            overlay_sha256: string;
            /** Rejected Entries */
            rejected_entries: components["schemas"]["DigiExamIngestionOverlayRejectedEntryV1"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "ingestion_overlay_report_v1";
            /** Source Ir Sha256 */
            source_ir_sha256: string;
        };
        /**
         * DigiExamItemType
         * @description Item types observed in DigiExam parser fixture corpora.
         * @enum {string}
         */
        DigiExamItemType: "open_ended" | "multiple_choice" | "single_choice" | "multiple_response" | "gap_fill" | "unknown";
        /**
         * DigiExamManualFollowUpPolicyV2
         * @description Allowed manual-follow-up reporting policy for DigiExam migration.
         * @enum {string}
         */
        DigiExamManualFollowUpPolicyV2: "emit_item_addressable_report";
        /**
         * DigiExamMigrationArtifactAvailability
         * @description Availability states for named bundle artifacts.
         * @enum {string}
         */
        DigiExamMigrationArtifactAvailability: "available" | "unavailable" | "failed" | "not_requested" | "not_implemented" | "not_supported_by_examnet";
        /**
         * DigiExamMigrationArtifactKey
         * @description Required artifact keys for DigiExam migration terminal bundles.
         * @enum {string}
         */
        DigiExamMigrationArtifactKey: "bundle_manifest" | "examnet_pdf" | "qti_package" | "qti_validation_report" | "ir_json" | "effective_ir_json" | "migration_manifest" | "target_readiness_report" | "ingestion_overlay_report" | "answer_key_completion_report" | "manual_follow_up_report" | "warnings_report" | "asset_summary";
        /**
         * DigiExamMigrationBundleArtifactEntryV2
         * @description One named artifact entry in a DigiExam migration bundle manifest.
         */
        DigiExamMigrationBundleArtifactEntryV2: {
            artifact_key: components["schemas"]["DigiExamMigrationArtifactKey"];
            availability: components["schemas"]["DigiExamMigrationArtifactAvailability"];
            /** Content Type */
            content_type: string;
            /**
             * Depends On
             * @default null
             */
            depends_on: string | null;
            /**
             * Download Path
             * @default null
             */
            download_path: string | null;
            /** Filename */
            filename: string;
            /**
             * Sha256
             * @default null
             */
            sha256: string | null;
            /**
             * Size Bytes
             * @default null
             */
            size_bytes: number | null;
            /**
             * Unavailable Code
             * @default null
             */
            unavailable_code: string | null;
        };
        /**
         * DigiExamMigrationBundleManifestV2
         * @description Terminal artifact bundle manifest for DigiExam migration jobs.
         */
        DigiExamMigrationBundleManifestV2: {
            /** Artifacts */
            artifacts: components["schemas"]["DigiExamMigrationBundleArtifactEntryV2"][];
            /**
             * Bundle Status
             * @enum {string}
             */
            bundle_status: "complete" | "partial" | "needs_review" | "failed";
            /** Job Id */
            job_id: string;
            manual_follow_up: components["schemas"]["DigiExamMigrationBundleManualFollowUpV2"];
            readiness: components["schemas"]["DigiExamMigrationBundleReadinessSummaryV2"];
            retention: components["schemas"]["DigiExamMigrationBundleRetentionV2"];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "digiexam_migration_bundle_v3";
            source: components["schemas"]["DigiExamMigrationBundleSourceV2"];
            source_binding: components["schemas"]["DigiExamMigrationBundleSourceBindingV2"];
            warnings: components["schemas"]["DigiExamMigrationBundleWarningsV2"];
        };
        /**
         * DigiExamMigrationBundleManualFollowUpV2
         * @description Manual follow-up summary in current DigiExam migration bundle manifests.
         */
        DigiExamMigrationBundleManualFollowUpV2: {
            /**
             * Artifact Key
             * @constant
             */
            artifact_key: "manual_follow_up_report";
            /** Count */
            count: number;
            /** Required */
            required: boolean;
        };
        /**
         * DigiExamMigrationBundleReadinessSummaryV2
         * @description Readiness summary pointing consumers to the authoritative report.
         */
        DigiExamMigrationBundleReadinessSummaryV2: {
            /**
             * Artifact Key
             * @constant
             */
            artifact_key: "target_readiness_report";
            /** Exportable Targets */
            exportable_targets?: string[];
            /** Review Required */
            review_required: boolean;
        };
        /**
         * DigiExamMigrationBundleRetentionV2
         * @description Retention summary in current DigiExam migration bundle manifests.
         */
        DigiExamMigrationBundleRetentionV2: {
            /**
             * Expires At
             * @default null
             */
            expires_at: string | null;
            /** Pin */
            pin: boolean;
        };
        /**
         * DigiExamMigrationBundleSourceBindingV2
         * @description Source/effective IR hashes published in bundle manifests.
         */
        DigiExamMigrationBundleSourceBindingV2: {
            /**
             * Effective Exam Schema Version
             * @constant
             */
            effective_exam_schema_version: "digiexam_effective_exam_v2";
            /** Effective Exam Sha256 */
            effective_exam_sha256: string;
            /**
             * Source Ir Schema Version
             * @constant
             */
            source_ir_schema_version: "digiexam_intermediate_exam_v3";
            /** Source Ir Sha256 */
            source_ir_sha256: string;
        };
        /**
         * DigiExamMigrationBundleSourceV2
         * @description Source summary in current DigiExam migration bundle manifests.
         */
        DigiExamMigrationBundleSourceV2: {
            /** Filename */
            filename: string;
            /**
             * Format
             * @constant
             */
            format: "digiexam_dxe";
            /** Sha256 */
            sha256: string;
        };
        /**
         * DigiExamMigrationBundleWarningsV2
         * @description Warnings summary in current DigiExam migration bundle manifests.
         */
        DigiExamMigrationBundleWarningsV2: {
            /**
             * Artifact Key
             * @constant
             */
            artifact_key: "warnings_report";
            /** Count */
            count: number;
        };
        /**
         * DigiExamMigrationConversionMetadataV2
         * @description Route-specific result metadata for DigiExam migration bundles.
         */
        DigiExamMigrationConversionMetadataV2: {
            /** Acceleration Policy Requested */
            acceleration_policy_requested?: string | null;
            /** Acceleration Used */
            acceleration_used?: string | null;
            /** Artifact Count */
            artifact_count: number;
            /** Backend Used */
            backend_used?: string | null;
            /**
             * Bundle Schema Version
             * @constant
             */
            bundle_schema_version: "digiexam_migration_bundle_v3";
            /**
             * Bundle Status
             * @enum {string}
             */
            bundle_status: "complete" | "partial" | "needs_review" | "failed";
            /** Chunk Size Pages */
            chunk_size_pages?: number | null;
            /** Effective Gpu Stage Limit */
            effective_gpu_stage_limit?: number | null;
            /** Gpu Busy Percent */
            gpu_busy_percent?: number | null;
            /** Gpu Device Count */
            gpu_device_count?: number | null;
            /** Gpu Memory Used Percent */
            gpu_memory_used_percent?: number | null;
            /** Gpu Runtime Kind */
            gpu_runtime_kind?: string | null;
            /** Manual Follow Up Required */
            manual_follow_up_required: boolean;
            /** Max Chunk Workers */
            max_chunk_workers?: number | null;
            /** Ocr Enabled */
            ocr_enabled?: boolean | null;
            /** Ocr Engine Used */
            ocr_engine_used?: string | null;
            /** Ocr Languages Used */
            ocr_languages_used?: string[] | null;
            /** Options Fingerprint */
            options_fingerprint: string;
            /** Parallel Enabled */
            parallel_enabled?: boolean | null;
            /** Pipeline Used */
            pipeline_used: string;
            /**
             * Route Key
             * @constant
             */
            route_key: "digiexam_dxe_to_examnet_migration_bundle";
            /** Scheduling Mode */
            scheduling_mode?: string | null;
            /** Source Sha256 */
            source_sha256: string;
            /**
             * Target Readiness Report Artifact Key
             * @constant
             */
            target_readiness_report_artifact_key: "target_readiness_report";
            /** Template Artifact Sha256 */
            template_artifact_sha256?: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Template Version */
            template_version?: string | null;
            /** Warning Count */
            warning_count: number;
        };
        /**
         * DigiExamMigrationOptionsV2
         * @description Route-specific options for DigiExam migration bundle jobs.
         */
        DigiExamMigrationOptionsV2: {
            /** @default source_evidence_only */
            completion_mode: components["schemas"]["DigiExamAnswerKeyCompletionModeV2"];
            /**
             * Graded Result Pdf Filename
             * @default null
             */
            graded_result_pdf_filename: string | null;
            /**
             * Ingestion Overlay Filename
             * @default null
             */
            ingestion_overlay_filename: string | null;
            /** @default none */
            ingestion_overlay_policy: components["schemas"]["DigiExamIngestionOverlayPolicyV2"];
            /** @default emit_item_addressable_report */
            manual_follow_up_policy: components["schemas"]["DigiExamManualFollowUpPolicyV2"];
            /**
             * Parity Pdf Filename
             * @default null
             */
            parity_pdf_filename: string | null;
            /** @default forbidden */
            remote_provider_policy: components["schemas"]["DigiExamRemoteProviderPolicyV2"];
            /** @default correct_machine_marked_answers_only */
            result_pdf_usage: components["schemas"]["DigiExamResultPdfUsageV2"];
        };
        /**
         * DigiExamOverlayChoiceAlternativeOverride
         * @description Bounded alternative text patch for effective choice items.
         */
        DigiExamOverlayChoiceAlternativeOverride: {
            /** Alternative Id */
            alternative_id: number;
            /** Text */
            text: string;
        };
        /**
         * DigiExamOverlayChoiceItemPatch
         * @description Bounded choice item patch applied only to the effective IR.
         */
        DigiExamOverlayChoiceItemPatch: {
            /**
             * Alternative Overrides
             * @default []
             */
            alternative_overrides: components["schemas"]["DigiExamOverlayChoiceAlternativeOverride"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "choice";
            /**
             * Prompt Html
             * @default null
             */
            prompt_html: string | null;
            /**
             * Prompt Lines
             * @default null
             */
            prompt_lines: string[] | null;
            /**
             * Title
             * @default null
             */
            title: string | null;
        };
        /**
         * DigiExamOverlayChoiceManualAnswerKey
         * @description Manual answer key for source choice items.
         */
        DigiExamOverlayChoiceManualAnswerKey: {
            /** Correct Alternative Ids */
            correct_alternative_ids: number[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "choice";
        };
        /**
         * DigiExamOverlayGapAnswer
         * @description Manual accepted values for one source gap.
         */
        DigiExamOverlayGapAnswer: {
            /** Accepted Values */
            accepted_values: string[];
            /** Gap Id */
            gap_id: string;
        };
        /**
         * DigiExamOverlayGapFillItemPatch
         * @description Bounded gap-fill item patch applied only to the effective IR.
         */
        DigiExamOverlayGapFillItemPatch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "gap_fill";
            /**
             * Prompt Html
             * @default null
             */
            prompt_html: string | null;
            /**
             * Prompt Lines
             * @default null
             */
            prompt_lines: string[] | null;
            /**
             * Title
             * @default null
             */
            title: string | null;
        };
        /**
         * DigiExamOverlayGapFillManualAnswerKey
         * @description Manual answer key for source gap-fill items.
         */
        DigiExamOverlayGapFillManualAnswerKey: {
            /** Gap Answers */
            gap_answers: components["schemas"]["DigiExamOverlayGapAnswer"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "gap_fill";
        };
        /**
         * DigiExamOverlayReviewDecision
         * @description Teacher review decision that never creates answer-key evidence.
         */
        DigiExamOverlayReviewDecision: {
            /** Accepted Targets */
            accepted_targets: components["schemas"]["ExamMigrationTargetV2"][];
            /** Decision Id */
            decision_id: string;
            /**
             * Kind
             * @constant
             */
            kind: "accept_current_state_for_export";
            /**
             * Note
             * @default null
             */
            note: string | null;
        };
        /**
         * DigiExamOverlayReviewedChoiceAnswerPayload
         * @description Reviewed choice answer payload using Task 297 candidate semantics.
         */
        DigiExamOverlayReviewedChoiceAnswerPayload: {
            /** Correct Alternative Ids */
            correct_alternative_ids: number[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "choice";
        };
        /**
         * DigiExamOverlayReviewedCompletionAnswerKey
         * @description Teacher-reviewed advisory answer key applied only to effective IR.
         */
        DigiExamOverlayReviewedCompletionAnswerKey: {
            /** Answer Payload */
            answer_payload: components["schemas"]["DigiExamOverlayReviewedChoiceAnswerPayload"] | components["schemas"]["DigiExamOverlayReviewedGapFillAnswerPayload"];
            candidate_lineage: components["schemas"]["DigiExamOverlayReviewedCompletionCandidateLineage"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "choice" | "gap_fill";
            /** Review Decision Id */
            review_decision_id: string;
            review_outcome: components["schemas"]["DigiExamOverlayReviewedCompletionOutcome"];
        };
        /**
         * DigiExamOverlayReviewedCompletionCandidateLineage
         * @description Bounded lineage for a reviewed advisory answer-key candidate.
         */
        DigiExamOverlayReviewedCompletionCandidateLineage: {
            /** Candidate Id */
            candidate_id: string;
            /** Candidate Payload Digest */
            candidate_payload_digest: string;
            /** Completion Report Sha256 */
            completion_report_sha256: string;
            /** Prompt Template Version */
            prompt_template_version: string;
            /** Provider Profile Id */
            provider_profile_id: string;
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            /**
             * Validation State
             * @constant
             */
            validation_state: "valid";
        };
        /**
         * DigiExamOverlayReviewedCompletionOutcome
         * @description Teacher review outcomes for applying an advisory candidate.
         * @enum {string}
         */
        DigiExamOverlayReviewedCompletionOutcome: "accepted_unchanged" | "teacher_edited";
        /**
         * DigiExamOverlayReviewedGapFillAnswerPayload
         * @description Reviewed gap-fill answer payload using Task 305 candidate semantics.
         */
        DigiExamOverlayReviewedGapFillAnswerPayload: {
            /** Gap Answers */
            gap_answers: components["schemas"]["DigiExamOverlayGapAnswer"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "gap_fill";
        };
        /**
         * DigiExamOverlaySourceBinding
         * @description Source binding required for a trusted overlay.
         */
        DigiExamOverlaySourceBinding: {
            /** Source File Sha256 */
            source_file_sha256: string;
            /**
             * Source Ir Schema Version
             * @constant
             */
            source_ir_schema_version: "digiexam_intermediate_exam_v3";
            /** Source Ir Sha256 */
            source_ir_sha256: string;
        };
        /**
         * DigiExamRemoteProviderPolicyV2
         * @description Allowed remote-provider policies for DigiExam answer-key completion.
         * @enum {string}
         */
        DigiExamRemoteProviderPolicyV2: "forbidden";
        /**
         * DigiExamResultPdfUsageV2
         * @description Allowed use of optional DigiExam graded-result PDF evidence.
         * @enum {string}
         */
        DigiExamResultPdfUsageV2: "correct_machine_marked_answers_only";
        /**
         * DigiExamTargetReadiness
         * @description Consumer-facing readiness classes for export targets.
         * @enum {string}
         */
        DigiExamTargetReadiness: "ready" | "ready_after_accepted_current_state" | "needs_teacher_answer_key" | "needs_teacher_review_decision" | "unsupported_target_shape" | "target_validation_failed" | "provider_unavailable" | "not_requested" | "not_implemented";
        /**
         * DigiExamTargetReadinessReportV1
         * @description Authoritative target-readiness report for migration bundle consumers.
         */
        DigiExamTargetReadinessReportV1: {
            /** Effective Exam Sha256 */
            effective_exam_sha256: string;
            /** Job Id */
            job_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "target_readiness_report_v1";
            /** Source Ir Sha256 */
            source_ir_sha256: string;
            /** Targets */
            targets: components["schemas"]["DigiExamTargetReadinessRowV1"][];
        };
        /**
         * DigiExamTargetReadinessRowV1
         * @description One target or target/item readiness row consumed by Skriptoteket.
         */
        DigiExamTargetReadinessRowV1: {
            /**
             * Artifact Key
             * @default null
             */
            artifact_key: string | null;
            /** Export Enabled */
            export_enabled: boolean;
            /**
             * Item Id
             * @default null
             */
            item_id: string | null;
            /** Message Key */
            message_key: string;
            readiness: components["schemas"]["DigiExamTargetReadiness"];
            /** Reason Code */
            reason_code: string;
            /** Retryable */
            retryable: boolean;
            /**
             * Sequence
             * @default null
             */
            sequence: number | null;
            /**
             * Source Item Fingerprint
             * @default null
             */
            source_item_fingerprint: string | null;
            /** Target */
            target: string;
            /** Teacher Action */
            teacher_action: string;
        };
        /**
         * ExamMigrationTargetV2
         * @description Supported target artifacts for exam-migration bundle routes.
         * @enum {string}
         */
        ExamMigrationTargetV2: "examnet_pdf" | "qti_package";
        /**
         * ExecutionSpecV2
         * @description Execution section of the v2 job specification.
         */
        ExecutionSpecV2: {
            acceleration_policy: components["schemas"]["AccelerationPolicy"];
            /**
             * Document Timeout Seconds
             * @default 1800
             */
            document_timeout_seconds: number;
            /** @default normal */
            priority: components["schemas"]["Priority"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreateResponseV2
         * @description Response payload for v2 job creation endpoints.
         */
        JobCreateResponseV2: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            job: components["schemas"]["JobRecordDataV2"];
            public_artifact_read_lease?: components["schemas"]["PublicArtifactReadLeaseResponseV2"] | null;
        };
        /**
         * JobLinksV2
         * @description Hypermedia links included in v2 job status payloads.
         */
        JobLinksV2: {
            /** Artifact */
            artifact: string;
            /** Cancel */
            cancel: string;
            /** Result */
            result: string;
            /** Self */
            self: string;
        };
        /**
         * JobPendingResultResponseV2
         * @description Response payload when a v2 result request is made before completion.
         */
        JobPendingResultResponseV2: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobProgressV2
         * @description Progress metadata for running v2 jobs.
         */
        JobProgressV2: {
            /** Current Phase Started At */
            current_phase_started_at?: string | null;
            /** Eta Seconds */
            eta_seconds?: number | null;
            /** Failed Pages */
            failed_pages?: number | null;
            /** Last Heartbeat At */
            last_heartbeat_at?: string | null;
            /** Pages Per Minute */
            pages_per_minute?: number | null;
            /** Percent Complete */
            percent_complete?: number | null;
            /**
             * Phase Timings Ms
             * @description Canonical stage timings map. See v2 converter docs for key contract.
             */
            phase_timings_ms?: {
                [key: string]: number;
            };
            /** Processed Pages */
            processed_pages?: number | null;
            /** Stage */
            stage: string;
            /** Total Pages */
            total_pages?: number | null;
        };
        /**
         * JobRecordDataV2
         * @description Job details payload embedded in v2 job record responses.
         */
        JobRecordDataV2: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /** Job Id */
            job_id: string;
            links: components["schemas"]["JobLinksV2"];
            output_format: components["schemas"]["OutputFormatV2"];
            progress: components["schemas"]["JobProgressV2"];
            /** Source Filename */
            source_filename: string;
            source_format: components["schemas"]["SourceFormatV2"];
            status: components["schemas"]["JobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobRecordResponseV2
         * @description Response payload for v2 job status endpoints.
         */
        JobRecordResponseV2: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            job: components["schemas"]["JobRecordDataV2"];
        };
        /**
         * JobResultResponseV2
         * @description Response payload for v2 successful result retrieval.
         */
        JobResultResponseV2: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            /** Job Id */
            job_id: string;
            result: components["schemas"]["ResultPayloadV2"];
            /**
             * Status
             * @default succeeded
             * @constant
             */
            status: "succeeded";
        };
        /**
         * JobSpecV2
         * @description Complete v2 job specification.
         */
        JobSpecV2: {
            /**
             * Api Version
             * @constant
             */
            api_version: "v2";
            conversion: components["schemas"]["ConversionSpecV2"];
            /** @default null */
            digiexam_migration_options: components["schemas"]["DigiExamMigrationOptionsV2"] | null;
            /** @default null */
            execution: components["schemas"]["ExecutionSpecV2"] | null;
            /** @default null */
            pdf_options: components["schemas"]["PdfOptionsV2"] | null;
            retention?: components["schemas"]["RetentionSpecV2"];
            source: components["schemas"]["SourceSpecV2"];
        };
        /**
         * JobStatus
         * @description Job status lifecycle states.
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "canceled";
        /**
         * NormalizeMode
         * @description Normalization modes supported by v1.
         * @enum {string}
         */
        NormalizeMode: "none" | "standard" | "strict";
        /**
         * OcrEngineV2
         * @description Supported OCR engines for PDF OCR stages.
         * @enum {string}
         */
        OcrEngineV2: "auto" | "easyocr" | "tesseract_cli";
        /**
         * OcrMode
         * @description OCR mode values supported by v1.
         * @enum {string}
         */
        OcrMode: "auto" | "off" | "force";
        /**
         * OutputFormatV2
         * @description Supported output formats for v2.
         * @enum {string}
         */
        OutputFormatV2: "md" | "pdf" | "docx" | "examnet_migration_bundle";
        /**
         * PdfCheckpointV2
         * @description Durable checkpoint state for chunked PDF-to-markdown execution.
         */
        PdfCheckpointV2: {
            /** Chunk Size Pages */
            chunk_size_pages: number;
            /** Chunks */
            chunks?: components["schemas"]["PdfChunkRecordV2"][];
            /** Failed Pages */
            failed_pages: number;
            /** Job Id */
            job_id: string;
            /** Processed Pages */
            processed_pages: number;
            /**
             * Schema Version
             * @default v2_pdf_checkpoint_v2
             * @constant
             */
            schema_version: "v2_pdf_checkpoint_v2";
            /** Total Pages */
            total_pages?: number | null;
            /** Updated At */
            updated_at: string;
        };
        /**
         * PdfChunkRecordV2
         * @description One persisted chunk record for a PDF conversion.
         */
        PdfChunkRecordV2: {
            /** Acceleration Used */
            acceleration_used: string;
            /** Artifact Relpath */
            artifact_relpath: string;
            /** Backend Used */
            backend_used: string;
            /** Chunk Index */
            chunk_index: number;
            /** Completed At */
            completed_at?: string | null;
            /** End Page */
            end_page: number;
            /** Ocr Enabled */
            ocr_enabled: boolean;
            /** Ocr Engine Used */
            ocr_engine_used?: string | null;
            /** Ocr Languages Used */
            ocr_languages_used?: string[];
            /** Phase Timings Ms */
            phase_timings_ms?: {
                [key: string]: number;
            };
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Start Page */
            start_page: number;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "failed";
            /** Warnings */
            warnings?: string[];
        };
        /**
         * PdfLayoutV2
         * @description Typed PDF layout presets for v2 PDF outputs.
         */
        PdfLayoutV2: {
            /**
             * Margins Mm
             * @default 12
             */
            margins_mm: number;
            /** @default portrait */
            orientation: components["schemas"]["PdfOrientationV2"];
            /** @default a4 */
            paper_size: components["schemas"]["PdfPaperSizeV2"];
        };
        /**
         * PdfOptionsV2
         * @description PDF-to-intermediate options for v2 routes that start from a PDF.
         */
        PdfOptionsV2: {
            backend_strategy: components["schemas"]["BackendStrategy"];
            normalize: components["schemas"]["NormalizeMode"];
            /**
             * @description OCR engine selection. 'auto' delegates to runtime defaults.
             * @default auto
             */
            ocr_engine: components["schemas"]["OcrEngineV2"];
            /**
             * Ocr Languages
             * @description Requested OCR languages as BCP47/ISO639-1 tags (e.g. ['sv','en']). Empty list delegates to runtime defaults.
             */
            ocr_languages?: string[];
            ocr_mode: components["schemas"]["OcrMode"];
            table_mode: components["schemas"]["TableMode"];
        };
        /**
         * PdfOrientationV2
         * @description Supported PDF orientations for v2 PDF outputs.
         * @enum {string}
         */
        PdfOrientationV2: "portrait" | "landscape";
        /**
         * PdfPageCssModeV2
         * @description Control whether PDF routes append service page CSS or trust author CSS.
         * @enum {string}
         */
        PdfPageCssModeV2: "preset_append" | "author_owned";
        /**
         * PdfPaperSizeV2
         * @description Supported PDF paper sizes for v2 PDF outputs.
         * @enum {string}
         */
        PdfPaperSizeV2: "a5" | "a4" | "a3";
        /**
         * Priority
         * @description Execution priority values supported by v1.
         * @enum {string}
         */
        Priority: "normal" | "high";
        /**
         * PublicArtifactReadLeaseResponseV2
         * @description Response fragment carrying a server-to-server artifact-read lease.
         */
        PublicArtifactReadLeaseResponseV2: {
            /** Artifact Key */
            artifact_key: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Token */
            token: string;
        };
        /**
         * ResultPayloadV2
         * @description Result payload for successful v2 conversion jobs.
         */
        ResultPayloadV2: {
            artifact: components["schemas"]["ArtifactMetadataV2"];
            /** Conversion Metadata */
            conversion_metadata: components["schemas"]["DigiExamMigrationConversionMetadataV2"] | components["schemas"]["ConversionMetadataV2"];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * RetentionSpecV2
         * @description Retention section of the v2 job specification.
         */
        RetentionSpecV2: {
            /**
             * Pin
             * @default false
             */
            pin: boolean;
        };
        /**
         * ServiceHealthResponse
         * @description Liveness payload for `/healthz`.
         */
        ServiceHealthResponse: {
            /** Data Root */
            data_root: string;
            /** Service Profile */
            service_profile: string;
            /** Service Revision */
            service_revision: string;
            /** Started At */
            started_at: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * SourceFormatV2
         * @description Supported uploaded source formats for v2.
         * @enum {string}
         */
        SourceFormatV2: "pdf" | "md" | "html" | "docx" | "digiexam_dxe";
        /**
         * SourceKindV2
         * @description Supported source kinds for v2 conversion requests.
         * @enum {string}
         */
        SourceKindV2: "upload";
        /**
         * SourceSpecV2
         * @description Source section of the v2 job specification.
         */
        SourceSpecV2: {
            /** Filename */
            filename: string;
            format: components["schemas"]["SourceFormatV2"];
            kind: components["schemas"]["SourceKindV2"];
        };
        /**
         * TableMode
         * @description Table extraction modes supported by v1.
         * @enum {string}
         */
        TableMode: "fast" | "accurate";
        /**
         * TemplateSelectorV2
         * @description Template selector for DOCX-producing v2 routes.
         */
        TemplateSelectorV2: {
            /** Template Id */
            template_id: string;
            /**
             * Version
             * @default null
             */
            version: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebhookSecretRevokeRequestV2
         * @description Request payload for webhook secret revocation.
         */
        WebhookSecretRevokeRequestV2: {
            /** Version */
            version?: ("active" | "next") | null;
        };
        /**
         * WebhookSecretRotateRequestV2
         * @description Request payload for webhook secret rotation.
         */
        WebhookSecretRotateRequestV2: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * WebhookSubscriptionCreateRequestV2
         * @description Request payload for webhook subscription creation.
         */
        WebhookSubscriptionCreateRequestV2: {
            /** Callback Url */
            callback_url: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Event Types */
            event_types: ("job.queued" | "job.running" | "job.succeeded" | "job.failed" | "job.canceled")[];
        };
        /**
         * WebhookSubscriptionUpdateRequestV2
         * @description Request payload for webhook subscription update.
         */
        WebhookSubscriptionUpdateRequestV2: {
            /** Callback Url */
            callback_url?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Event Types */
            event_types?: ("job.queued" | "job.running" | "job.succeeded" | "job.failed" | "job.canceled")[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceHealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    readycheck_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_job_v2_convert_jobs_post: {
        parameters: {
            query?: {
                wait_seconds?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_v2_convert_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreateResponseV2"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreateResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v2_convert_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecordResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_v2_convert_jobs__job_id__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPendingResultResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_partial_artifact_v2_convert_jobs__job_id__artifact_partial_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPendingResultResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_bundle_manifest_v2_convert_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigiExamMigrationBundleManifestV2"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPendingResultResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_named_artifact_v2_convert_jobs__job_id__artifacts__artifact_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                artifact_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPendingResultResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v2_convert_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecordResponseV2"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecordResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_v2_convert_jobs__job_id__checkpoint_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PdfCheckpointV2"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPendingResultResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_events_v2_convert_jobs__job_id__events_stream_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                last_event_id?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_v2_convert_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultResponseV2"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPendingResultResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_v2_convert_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecordResponseV2"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecordResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subscriptions_v2_push_webhooks_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_subscription_v2_push_webhooks_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookSubscriptionCreateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_v2_push_webhooks_subscriptions__subscription_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_v2_push_webhooks_subscriptions__subscription_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subscription_v2_push_webhooks_subscriptions__subscription_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookSubscriptionUpdateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_secret_v2_push_webhooks_subscriptions__subscription_id__revoke_secret_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookSecretRevokeRequestV2"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_secret_v2_push_webhooks_subscriptions__subscription_id__rotate_secret_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookSecretRotateRequestV2"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_docx_templates_v2_templates_docx_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_docx_template_v2_templates_docx__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_docx_template_version_v2_templates_docx__template_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
