<script setup lang="ts">
/**
 * Signed-out landing preview for Klassrumskartan.
 *
 * This component owns the decorative classroom SVG used in the public-entry
 * hero so the landing route can keep layout and copy separate from preview
 * illustration markup.
 */
</script>

<template>
  <aside
    class="hero-preview"
    aria-label="Förhandsvisning av Klassrumskartan"
  >
    <svg
      class="block h-auto w-full"
      viewBox="0 0 320 220"
      role="img"
      aria-label="Klassrum med whiteboard, dörr och placerade elever"
    >
      <rect
        x="2"
        y="2"
        width="316"
        height="216"
        fill="none"
        stroke="var(--color-navy)"
        stroke-width="2"
      />
      <rect
        x="16"
        y="16"
        width="124"
        height="22"
        fill="var(--color-navy)"
        fill-opacity="0.06"
        stroke="var(--color-navy)"
        stroke-width="2"
      />
      <text
        x="78"
        y="32"
        font-family="var(--font-mono)"
        font-size="9"
        font-weight="700"
        fill="var(--color-navy)"
        fill-opacity="0.7"
        text-anchor="middle"
      >WHITEBOARD</text>
      <rect
        x="232"
        y="16"
        width="72"
        height="22"
        fill="var(--color-navy)"
        fill-opacity="0.06"
        stroke="var(--color-navy)"
        stroke-width="2"
      />
      <text
        x="268"
        y="32"
        font-family="var(--font-mono)"
        font-size="9"
        font-weight="700"
        fill="var(--color-navy)"
        fill-opacity="0.7"
        text-anchor="middle"
      >DÖRR</text>
      <g
        font-family="var(--font-sans)"
        font-size="10"
        fill="var(--color-navy)"
        font-weight="600"
      >
        <rect
          x="20"
          y="62"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="48"
          y="80"
          text-anchor="middle"
        >Ada</text>
        <rect
          x="92"
          y="62"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="120"
          y="80"
          text-anchor="middle"
        >Alan</text>
        <rect
          x="172"
          y="62"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="200"
          y="80"
          text-anchor="middle"
        >Karin</text>
        <rect
          x="244"
          y="62"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="272"
          y="80"
          text-anchor="middle"
        >Leo</text>

        <rect
          x="20"
          y="106"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="48"
          y="124"
          text-anchor="middle"
        >Mona</text>
        <rect
          x="92"
          y="106"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="120"
          y="124"
          text-anchor="middle"
        >Nils</text>
        <rect
          x="172"
          y="106"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="200"
          y="124"
          text-anchor="middle"
        >Sara</text>
        <rect
          x="244"
          y="106"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="272"
          y="124"
          text-anchor="middle"
        >Vera</text>

        <rect
          x="20"
          y="150"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="48"
          y="168"
          text-anchor="middle"
        >Yusuf</text>
        <rect
          x="92"
          y="150"
          width="56"
          height="28"
          fill="var(--color-canvas)"
          stroke="var(--color-navy)"
          stroke-width="2"
        />
        <text
          x="120"
          y="168"
          text-anchor="middle"
        >Eva</text>
        <rect
          x="172"
          y="150"
          width="56"
          height="28"
          fill="var(--color-navy)"
          fill-opacity="0.05"
          stroke="var(--color-navy)"
          stroke-width="2"
          stroke-dasharray="3,3"
        />
        <text
          x="200"
          y="168"
          text-anchor="middle"
          fill-opacity="0.4"
        >tom</text>
        <rect
          x="244"
          y="150"
          width="56"
          height="28"
          fill="var(--color-navy)"
          fill-opacity="0.05"
          stroke="var(--color-navy)"
          stroke-width="2"
          stroke-dasharray="3,3"
        />
        <text
          x="272"
          y="168"
          text-anchor="middle"
          fill-opacity="0.4"
        >tom</text>
      </g>
    </svg>
  </aside>
</template>

<style scoped>
.hero-preview {
  border: 2px solid var(--color-navy);
  background-color: var(--color-canvas);
  box-shadow: 4px 4px 0 0 var(--color-navy);
  padding: 1.125rem;
}
</style>
