"""python-docx writer for the native exam workspace document (D3 export).

Renders a native exam document as a Swedish Word export: title, instructions,
one Heading 3 section per item with body, points, and choices, plus a final
``Facit`` section for keyed items. ``validate_docx_bytes`` re-opens the
generated bytes and fails closed before the artifact is handed out.
"""

import io
import zipfile

from docx import Document
from docx.opc.exceptions import PackageNotFoundError

from skriptoteket.domain.curated_apps.exam_workspace.native_exam_document import (
    NativeExamDocument,
    NativeExamItem,
    NativeExamItemKind,
)
from skriptoteket.domain.errors import DomainError, ErrorCode

_ITEM_HEADING_STYLE = "Heading 3"
_CHOICE_KINDS = (
    NativeExamItemKind.SINGLE_CHOICE,
    NativeExamItemKind.MULTIPLE_RESPONSE,
)


class ExamWorkspaceDocxWriter:
    """Deterministic DOCX export via python-docx."""

    def build_docx_bytes(self, document: NativeExamDocument) -> bytes:
        output = Document()
        output.add_heading(document.title, level=1)
        for line in document.instructions:
            output.add_paragraph(line)

        for item in document.items:
            output.add_heading(_item_heading(item), level=3)
            for line in item.plain_text_lines():
                output.add_paragraph(line)
            output.add_paragraph(_points_line(item))
            if item.kind in _CHOICE_KINDS:
                for index, choice in enumerate(item.choices):
                    output.add_paragraph(f"{_choice_letter(index)}) {choice.text}")

        keyed_items = tuple(item for item in document.items if _facit_lines(item))
        if keyed_items:
            output.add_heading("Facit", level=2)
            for item in keyed_items:
                output.add_paragraph(_item_heading(item))
                for line in _facit_lines(item):
                    output.add_paragraph(line)

        buffer = io.BytesIO()
        output.save(buffer)
        return buffer.getvalue()

    def validate_docx_bytes(self, content: bytes, *, expected_item_count: int) -> None:
        """Fail-closed D3 validation: the export must re-open and keep all items."""
        try:
            parsed = Document(io.BytesIO(content))
        except (
            PackageNotFoundError,
            zipfile.BadZipFile,
            KeyError,
            ValueError,
        ) as error:
            raise DomainError(
                code=ErrorCode.VALIDATION_ERROR,
                message="Det genererade Word-dokumentet kunde inte läsas.",
            ) from error
        heading_count = sum(
            1
            for paragraph in parsed.paragraphs
            if paragraph.style is not None and paragraph.style.name == _ITEM_HEADING_STYLE
        )
        if heading_count != expected_item_count:
            raise DomainError(
                code=ErrorCode.VALIDATION_ERROR,
                message="Det genererade Word-dokumentet saknar förväntade frågerubriker.",
                details={
                    "expected_item_count": expected_item_count,
                    "found_item_headings": heading_count,
                },
            )


def _item_heading(item: NativeExamItem) -> str:
    return item.title or f"Fråga {item.sequence}"


def _points_line(item: NativeExamItem) -> str:
    if item.points is None:
        return "Poäng: saknas"
    return f"Poäng: {_format_points(item.points)} poäng"


def _format_points(points: int | float) -> str:
    if isinstance(points, int) or float(points).is_integer():
        return str(int(points))
    return str(points).replace(".", ",")


def _choice_letter(index: int) -> str:
    if index < 26:
        return chr(ord("A") + index)
    return str(index + 1)


def _facit_lines(item: NativeExamItem) -> tuple[str, ...]:
    if item.kind in _CHOICE_KINDS and item.answer_key.correct_choice_ids:
        text_by_choice_id = {choice.choice_id: choice.text for choice in item.choices}
        correct_texts = tuple(
            text_by_choice_id[choice_id] for choice_id in item.answer_key.correct_choice_ids
        )
        return (f"Rätt svar: {'; '.join(correct_texts)}",)
    if item.kind is NativeExamItemKind.GAP_FILL and any(gap.accepted_values for gap in item.gaps):
        return tuple(
            f"Lucka {index}: {' / '.join(gap.accepted_values)}"
            for index, gap in enumerate(item.gaps, start=1)
        )
    return ()
